'use strict';
const { test } = require('node:test');
const assert = require('node:assert');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const memory = require('../bin/yotta-memory.js');

const CLI = path.join(__dirname, '..', 'bin', 'yotta-memory.js');
const MARKER = 'Generated by yotta-memory lan enable';

function tmpDir(t, tag) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ytm-lan-' + tag + '-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  return dir;
}

function coreOpts(dir, extra) {
  return Object.assign({
    userId: 'TESTPC\\tester',
    nodePath: 'C:\\node\\node.exe',
    scriptPath: 'C:\\tools\\yotta-memory.js',
    logPath: path.join(dir, 'serve-8787.log'),
    xmlDir: dir,
    startupDir: path.join(dir, 'startup'),
    autostartDir: path.join(dir, 'autostart'),
  }, extra || {});
}

function winCliEnv(dir, extra) {
  const env = Object.assign({}, process.env);
  env.YOTTA_LAN_PLATFORM = 'win32';
  env.YOTTA_LAN_TASK_USER = 'TESTPC\\tester';
  env.YOTTA_LAN_TASK_XML_DIR = dir;
  env.YOTTA_LAN_STARTUP_DIR = path.join(dir, 'startup');
  env.YOTTA_LAN_AUTOSTART_DIR = path.join(dir, 'autostart');
  env.YOTTA_MEMORY_HOME = dir;
  return Object.assign(env, extra || {});
}

function runCli(args, env) {
  return spawnSync(process.execPath, [CLI].concat(args), { encoding: 'utf8', env: env });
}

function writeStub(dir, name, lines) {
  const stub = path.join(dir, name);
  fs.writeFileSync(stub, ["'use strict';"].concat(lines).join('\n') + '\n', 'utf8');
  return stub;
}

// ---- task XML (0.22.4: S4U silent principal, no battery / 72h limits) ----

test('Windows task XML uses an S4U principal and boot trigger without battery/time limits', () => {
  const xml = memory.lanWindowsTaskXml({
    trigger: 'onstart',
    userId: 'DESKTOP-BKLMU7E\\tester',
    nodePath: 'C:\\Program Files\\nodejs\\node.exe',
    scriptPath: 'C:\\tools\\yotta-memory.js',
    logPath: 'C:\\Users\\tester\\.yottamemory\\serve-8787.log',
    host: '0.0.0.0',
    port: 8787,
    cmdPath: 'C:\\Windows\\system32\\cmd.exe',
  });
  assert.match(xml, /<LogonType>S4U<\/LogonType>/);
  assert.match(xml, /<UserId>DESKTOP-BKLMU7E\\tester<\/UserId>/);
  assert.match(xml, /<BootTrigger>/);
  assert.doesNotMatch(xml, /<LogonTrigger>/);
  assert.match(xml, /<DisallowStartIfOnBatteries>false<\/DisallowStartIfOnBatteries>/);
  assert.match(xml, /<StopIfGoingOnBatteries>false<\/StopIfGoingOnBatteries>/);
  assert.match(xml, /<ExecutionTimeLimit>PT0S<\/ExecutionTimeLimit>/);
  assert.match(xml, /<StartWhenAvailable>true<\/StartWhenAvailable>/);
  assert.match(xml, /<Command>C:\\Windows\\system32\\cmd\.exe<\/Command>/);
  assert.match(xml, /"C:\\Program Files\\nodejs\\node\.exe" "C:\\tools\\yotta-memory\.js" serve --host 0\.0\.0\.0 --port 8787/);
  assert.match(xml, />> "C:\\Users\\tester\\\.yottamemory\\serve-8787\.log" 2>&amp;1/);
  assert.ok(!/&(?!amp;|lt;|gt;|quot;|apos;)/.test(xml), 'XML text must not contain raw & outside entities');
});

test('Windows task XML defaults to a logon trigger and escapes XML special characters', () => {
  const xml = memory.lanWindowsTaskXml({
    trigger: 'onlogon',
    userId: 'DOMAIN\\user&co',
    nodePath: 'C:\\node&tools\\node.exe',
    scriptPath: 'C:\\my tools\\yotta-memory.js',
    logPath: 'C:\\logs\\serve.log',
  });
  assert.match(xml, /<LogonTrigger>/);
  assert.doesNotMatch(xml, /<BootTrigger>/);
  assert.match(xml, /<UserId>DOMAIN\\user&amp;co<\/UserId>/);
  assert.match(xml, /C:\\node&amp;tools\\node\.exe/);
  assert.match(xml, /<Command>[^<]*cmd[^<]*<\/Command>/i);
  assert.ok(!/&(?!amp;|lt;|gt;|quot;|apos;)/.test(xml), 'XML text must not contain raw & outside entities');
});

test('task user resolution prefers explicit opts then the env override', () => {
  const prev = process.env.YOTTA_LAN_TASK_USER;
  try {
    assert.strictEqual(memory.lanWindowsTaskUser({ userId: 'EXPLICIT\\user' }), 'EXPLICIT\\user');
    process.env.YOTTA_LAN_TASK_USER = 'ENV\\user';
    assert.strictEqual(memory.lanWindowsTaskUser({}), 'ENV\\user');
  } finally {
    if (prev === undefined) delete process.env.YOTTA_LAN_TASK_USER;
    else process.env.YOTTA_LAN_TASK_USER = prev;
  }
});

// ---- enable core (register from XML, fallback to Startup) ----

test('Windows lan enable registers the S4U task from XML and cleans the temp file', (t) => {
  const dir = tmpDir(t, 'task');
  const calls = [];
  let xmlDuringCall = '';
  let xmlPathSeen = '';
  const result = memory.lanWindowsEnableCore(coreOpts(dir, {
    onstart: true,
    execFileFn: (command, args) => {
      calls.push({ command: command, args: args });
      const i = args.indexOf('/xml');
      xmlPathSeen = args[i + 1];
      xmlDuringCall = fs.readFileSync(xmlPathSeen, 'utf16le');
      return '';
    },
  }));
  assert.strictEqual(result.error, false);
  assert.strictEqual(result.mode, 'task');
  assert.strictEqual(result.trigger, 'onstart');
  assert.strictEqual(calls.length, 1);
  assert.strictEqual(calls[0].command, 'schtasks');
  assert.deepStrictEqual(calls[0].args.slice(0, 4), ['/create', '/tn', 'YottaMemoryServe', '/xml']);
  assert.strictEqual(calls[0].args[calls[0].args.length - 1], '/f');
  assert.ok(!calls[0].args.includes('/tr'), 'must not fall back to the legacy /tr command form');
  assert.ok(!calls[0].args.includes('/sc'), 'must not fall back to the legacy /sc trigger form');
  assert.match(xmlDuringCall, /<LogonType>S4U<\/LogonType>/);
  assert.match(xmlDuringCall, /<BootTrigger>/);
  assert.strictEqual(fs.existsSync(xmlPathSeen), false, 'temp task XML must be cleaned up');
  assert.deepStrictEqual(result.removedStartup, []);
});

test('task success removes stale Startup fallback files to avoid double autostart', (t) => {
  const dir = tmpDir(t, 'cleanup');
  const opts = coreOpts(dir, { execFileFn: () => '' });
  fs.mkdirSync(opts.startupDir, { recursive: true });
  fs.mkdirSync(opts.autostartDir, { recursive: true });
  const vbs = path.join(opts.startupDir, 'yotta-memory-serve.vbs');
  const cmd = path.join(opts.autostartDir, 'yotta-memory-autostart.cmd');
  fs.writeFileSync(vbs, "' " + MARKER, 'utf8');
  fs.writeFileSync(cmd, 'rem ' + MARKER, 'utf8');
  const result = memory.lanWindowsEnableCore(opts);
  assert.strictEqual(result.mode, 'task');
  assert.strictEqual(result.removedStartup.length, 2);
  assert.strictEqual(fs.existsSync(vbs), false);
  assert.strictEqual(fs.existsSync(cmd), false);
});

test('schtasks access denied falls back to the silent Startup path', (t) => {
  const dir = tmpDir(t, 'fallback');
  const result = memory.lanWindowsEnableCore(coreOpts(dir, {
    execFileFn: () => {
      const err = new Error('Access is denied.');
      err.stderr = 'ERROR: Access is denied.';
      throw err;
    },
  }));
  assert.strictEqual(result.error, false);
  assert.strictEqual(result.mode, 'startup');
  assert.strictEqual(result.accessDenied, true);
  assert.ok(fs.existsSync(result.vbsPath));
  assert.ok(fs.existsSync(result.cmdPath));
  const cmdContent = fs.readFileSync(result.cmdPath, 'utf8');
  assert.match(cmdContent, /serve --host 0\.0\.0\.0 --port 8787/);
  assert.match(cmdContent, /serve-8787\.log/);
  assert.match(cmdContent, new RegExp(MARKER));
  const vbsContent = fs.readFileSync(result.vbsPath, 'utf16le');
  assert.match(vbsContent, new RegExp(MARKER));
});

test('non-permission schtasks failure also falls back, without the access-denied flag', (t) => {
  const dir = tmpDir(t, 'fallback2');
  const result = memory.lanWindowsEnableCore(coreOpts(dir, {
    execFileFn: () => {
      const err = new Error('The task XML is malformed.');
      err.stderr = 'ERROR: The task XML is malformed.';
      throw err;
    },
  }));
  assert.strictEqual(result.error, false);
  assert.strictEqual(result.mode, 'startup');
  assert.strictEqual(result.accessDenied, false);
});

// ---- CLI wiring (stub schtasks binary through YOTTA_LAN_SCHTASKS_BIN) ----

test('lan status shows the logon mode from schtasks output', (t) => {
  const dir = tmpDir(t, 'status');
  const stub = writeStub(dir, 'schtasks-stub.js', [
    "console.log('状态: 就绪');",
    "console.log('登录模式: S4U');",
  ]);
  const r = runCli(['lan', 'status'], winCliEnv(dir, { YOTTA_LAN_SCHTASKS_BIN: stub }));
  assert.strictEqual(r.status, 0, r.stderr || r.stdout);
  assert.match(r.stdout, /计划任务 YottaMemoryServe: 已启用/);
  assert.match(r.stdout, /登录模式: S4U/);
  assert.doesNotMatch(r.stdout, /交互式/);
});

test('lan status warns when the legacy interactive task is still registered', (t) => {
  const dir = tmpDir(t, 'status-legacy');
  const stub = writeStub(dir, 'schtasks-stub.js', [
    "console.log('状态: 就绪');",
    "console.log('登录模式: 交互式');",
  ]);
  const r = runCli(['lan', 'status'], winCliEnv(dir, { YOTTA_LAN_SCHTASKS_BIN: stub }));
  assert.strictEqual(r.status, 0, r.stderr || r.stdout);
  assert.match(r.stdout, /登录模式: 交互式/);
  assert.match(r.stdout, /请重新执行 yotta-memory lan enable 修复/);
});

test('lan disable removes the task through the configured schtasks binary', (t) => {
  const dir = tmpDir(t, 'disable');
  const stub = writeStub(dir, 'schtasks-stub.js', []);
  const r = runCli(['lan', 'disable'], winCliEnv(dir, { YOTTA_LAN_SCHTASKS_BIN: stub }));
  assert.strictEqual(r.status, 0, r.stderr || r.stdout);
  assert.match(r.stdout, /已移除开机自启计划任务 YottaMemoryServe/);
});

test('lan disable treats a missing task as not enabled (no error exit)', (t) => {
  const dir = tmpDir(t, 'disable-missing');
  const stub = writeStub(dir, 'schtasks-stub.js', [
    "console.error('错误: 系统找不到指定的文件。');",
    'process.exit(1);',
  ]);
  const r = runCli(['lan', 'disable'], winCliEnv(dir, { YOTTA_LAN_SCHTASKS_BIN: stub }));
  assert.strictEqual(r.status, 0, r.stderr || r.stdout);
  assert.match(r.stdout, /未启用: 未发现任何自启配置/);
});

test('lan disable on a non-admin shell explains the admin fix for an access-denied task', (t) => {
  const dir = tmpDir(t, 'disable-denied');
  const stub = writeStub(dir, 'schtasks-stub.js', [
    "console.error('ERROR: Access is denied.');",
    'process.exit(1);',
  ]);
  const r = runCli(['lan', 'disable'], winCliEnv(dir, { YOTTA_LAN_SCHTASKS_BIN: stub }));
  assert.strictEqual(r.status, 1);
  assert.match(r.stderr, /移除计划任务失败: ERROR: Access is denied\./);
  assert.match(r.stderr, /请用管理员终端执行 yotta-memory lan disable/);
});

// ---- v0.22.5: Electron host (YottaCode shim) env injection ----

test('Windows task XML injects ELECTRON_RUN_AS_NODE under an Electron host', () => {
  const xml = memory.lanWindowsTaskXml({
    trigger: 'onstart',
    userId: 'DESKTOP-BKLMU7E\\tester',
    nodePath: 'C:\\Program Files\\YottaCode\\YottaCode.exe',
    scriptPath: 'C:\\Users\\tester\\.yottamemory\\runtime\\current\\bin\\yotta-memory.js',
    logPath: 'C:\\Users\\tester\\.yottamemory\\serve-8787.log',
    electronHost: true,
  });
  assert.match(xml, /set "ELECTRON_RUN_AS_NODE=1" &amp;&amp; "C:\\Program Files\\YottaCode\\YottaCode\.exe"/);
  assert.ok(!/&(?!amp;|lt;|gt;|quot;|apos;)/.test(xml), 'XML text must not contain raw & outside entities');

  const plain = memory.lanWindowsTaskXml({
    trigger: 'onlogon',
    nodePath: 'C:\\nodejs\\node.exe',
    scriptPath: 'C:\\tools\\yotta-memory.js',
    logPath: 'C:\\logs\\serve.log',
    electronHost: false,
  });
  assert.doesNotMatch(plain, /ELECTRON_RUN_AS_NODE/);
});

test('lan enable under an Electron host registers an env-injected task XML', (t) => {
  const dir = tmpDir(t, 'task-electron');
  let xmlDuringCall = '';
  const result = memory.lanWindowsEnableCore(coreOpts(dir, {
    electronHost: true,
    nodePath: 'C:\\Program Files\\YottaCode\\YottaCode.exe',
    execFileFn: (command, args) => {
      const i = args.indexOf('/xml');
      xmlDuringCall = fs.readFileSync(args[i + 1], 'utf16le');
      return '';
    },
  }));
  assert.strictEqual(result.error, false);
  assert.strictEqual(result.mode, 'task');
  assert.match(xmlDuringCall, /ELECTRON_RUN_AS_NODE=1/);
});

test('Startup fallback cmd injects the Electron env under an Electron host', (t) => {
  const dir = tmpDir(t, 'fallback-electron');
  const result = memory.lanWindowsEnableCore(coreOpts(dir, {
    electronHost: true,
    execFileFn: () => {
      const err = new Error('Access is denied.');
      err.stderr = 'ERROR: Access is denied.';
      throw err;
    },
  }));
  assert.strictEqual(result.mode, 'startup');
  const cmdContent = fs.readFileSync(result.cmdPath, 'utf8');
  assert.match(cmdContent, /set "ELECTRON_RUN_AS_NODE=1"/);
  const plain = memory.lanAutostartCmdContent({ electronHost: false, host: '0.0.0.0', port: 8787 });
  assert.doesNotMatch(plain, /ELECTRON_RUN_AS_NODE/);
});

test('daily backup task wraps an Electron host with cmd + env', () => {
  const xml = memory.backupWindowsTaskXml({
    time: '03:30',
    nodePath: 'C:\\Program Files\\YottaCode\\YottaCode.exe',
    scriptPath: 'C:\\tools\\yotta-memory.js',
    userId: 'TESTPC\\tester',
    electronHost: true,
    cmdPath: 'C:\\Windows\\system32\\cmd.exe',
  });
  assert.match(xml, /<Command>C:\\Windows\\system32\\cmd\.exe<\/Command>/);
  assert.match(xml, /set "ELECTRON_RUN_AS_NODE=1" &amp;&amp; "C:\\Program Files\\YottaCode\\YottaCode\.exe" "C:\\tools\\yotta-memory\.js" backup ensure-daily/);
  const plain = memory.backupWindowsTaskXml({
    time: '03:30',
    nodePath: 'C:\\nodejs\\node.exe',
    scriptPath: 'C:\\tools\\yotta-memory.js',
    electronHost: false,
  });
  assert.match(plain, /<Command>C:\\nodejs\\node\.exe<\/Command>/);
  assert.doesNotMatch(plain, /ELECTRON_RUN_AS_NODE/);
});

test('Linux autostart and backup generators inject the Electron env', () => {
  const unit = memory.lanLinuxUnitContent({ host: '127.0.0.1', port: 8787, electronHost: true });
  assert.match(unit, /Environment=ELECTRON_RUN_AS_NODE=1/);
  const line = memory.lanCrontabLine({ host: '127.0.0.1', port: 8787, electronHost: true });
  assert.match(line, /^@reboot ELECTRON_RUN_AS_NODE=1 /);
  const backupService = memory.backupSystemdServiceContent({ nodePath: '/opt/YottaCode/yottacode', scriptPath: '/opt/ytm/yotta-memory.js', electronHost: true });
  assert.match(backupService, /Environment=ELECTRON_RUN_AS_NODE=1/);
  const backupCron = memory.backupCronLine({ time: '03:30', nodePath: '/opt/YottaCode/yottacode', scriptPath: '/opt/ytm/yotta-memory.js', electronHost: true });
  assert.match(backupCron, /\* \* \* ELECTRON_RUN_AS_NODE=1 /);

  const plainUnit = memory.lanLinuxUnitContent({ host: '127.0.0.1', port: 8787, electronHost: false });
  assert.doesNotMatch(plainUnit, /ELECTRON_RUN_AS_NODE/);
  const plainLine = memory.lanCrontabLine({ host: '127.0.0.1', port: 8787, electronHost: false });
  assert.doesNotMatch(plainLine, /ELECTRON_RUN_AS_NODE/);
});

test('macOS backup LaunchAgent injects the Electron env', () => {
  const plist = memory.backupLaunchdPlist({ time: '03:30', nodePath: '/Applications/YottaCode.app/yottacode', scriptPath: '/opt/ytm/yotta-memory.js', electronHost: true });
  assert.match(plist, /<key>EnvironmentVariables<\/key><dict><key>ELECTRON_RUN_AS_NODE<\/key><string>1<\/string><\/dict>/);
  const plain = memory.backupLaunchdPlist({ time: '03:30', nodePath: '/usr/local/bin/node', scriptPath: '/opt/ytm/yotta-memory.js', electronHost: false });
  assert.doesNotMatch(plain, /ELECTRON_RUN_AS_NODE/);
});

test('lan status warns when the task launches an Electron exe without the env', (t) => {
  const dir = tmpDir(t, 'status-electron');
  const stub = writeStub(dir, 'schtasks-stub.js', [
    "console.log('状态: 就绪');",
    "console.log('登录模式: S4U');",
    "console.log('要运行的任务: \"C:\\\\Program Files\\\\YottaCode\\\\YottaCode.exe\" \"C:\\\\Users\\\\t\\\\.yottamemory\\\\runtime\\\\current\\\\bin\\\\yotta-memory.js\" serve --host 0.0.0.0 --port 8787');",
  ]);
  const r = runCli(['lan', 'status'], winCliEnv(dir, { YOTTA_LAN_SCHTASKS_BIN: stub }));
  assert.strictEqual(r.status, 0, r.stderr || r.stdout);
  assert.match(r.stdout, /缺少 ELECTRON_RUN_AS_NODE/);
});

test('lan status does not warn when the task already injects the env', (t) => {
  const dir = tmpDir(t, 'status-electron-fixed');
  const stub = writeStub(dir, 'schtasks-stub.js', [
    "console.log('状态: 就绪');",
    "console.log('登录模式: S4U');",
    "console.log('要运行的任务: cmd.exe /c \"set \"ELECTRON_RUN_AS_NODE=1\" && \"C:\\\\Program Files\\\\YottaCode\\\\YottaCode.exe\" serve\"');",
  ]);
  const r = runCli(['lan', 'status'], winCliEnv(dir, { YOTTA_LAN_SCHTASKS_BIN: stub }));
  assert.strictEqual(r.status, 0, r.stderr || r.stdout);
  assert.doesNotMatch(r.stdout, /缺少 ELECTRON_RUN_AS_NODE/);
});
